name: finis-client
services:
  main:
    image: node:latest
    ports:
      - "80:5173"
    volumes:
      - ..:/workspace
    command:
      - sleep infinity
    networks:
      - finis-network
networks:
  finis-network:
    name: finis-network
    external: true